#!/usr/bin/env python3
"""Regenerate icu/versions.nix from the icu majors the pinned nixpkgs carries.

icu's passthru.wasix.retentionHook: nixpkgs adds and drops icu majors over time
(icu69 was removed, icu78 arrived), and the icu/icu-data families plus the
default-alias major must track exactly what nixpkgs exposes, or `prev.icuNN`
throws. The update driver runs this after history retention and rel pruning.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

SYSTEM = "x86_64-linux"
REPO = Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        text=True,
        capture_output=True,
        check=True,
    ).stdout.strip()
)
VERSIONS = REPO / "pkgs/overlay/packages/icu/versions.nix"


def nixpkgs_flakeref():
    # Resolve the PINNED nixpkgs straight from flake.lock, not through the repo
    # flake: a stale versions.nix (a major nixpkgs just dropped) makes prev.icuNN
    # throw and the repo eval fail, which is exactly the state this hook repairs.
    node = json.loads((REPO / "flake.lock").read_text())["nodes"]["nixpkgs"]["locked"]
    t = node["type"]
    if t in ("github", "gitlab", "sourcehut"):
        return f"{t}:{node['owner']}/{node['repo']}/{node['rev']}"
    if t == "git":
        return f"git+{node['url']}?rev={node['rev']}"
    if node.get("url"):
        return node["url"]
    raise SystemExit(f"cannot build a flakeref for nixpkgs input: {node}")


def available_majors():
    # attrNames does not force the values; tryEval on each icuNN.version drops
    # the throwing aliases nixpkgs leaves behind for a removed major.
    attrs = json.loads(
        subprocess.run(
            [
                "nix",
                "eval",
                "--json",
                f"{nixpkgs_flakeref()}#legacyPackages.{SYSTEM}",
                "--apply",
                'pkgs: builtins.filter (n: (builtins.match "icu[0-9]+" n) != null '
                "&& (let r = builtins.tryEval (pkgs.${n}.version or null); "
                "in r.success && r.value != null)) (builtins.attrNames pkgs)",
            ],
            cwd=REPO,
            text=True,
            capture_output=True,
            check=True,
        ).stdout
    )
    return sorted({re.fullmatch(r"icu(\d+)", a).group(1) for a in attrs}, key=int)


def main():
    majors = available_majors()
    old = VERSIONS.read_text() if VERSIONS.exists() else ""
    old_majors = re.findall(r'"(\d+)"', old)  # quoted entries only, never a comment
    if majors == old_majors:
        print("versions.nix up to date")
        return
    body = " ".join(f'"{m}"' for m in majors)
    VERSIONS.write_text(
        "# icu majors present in nixpkgs, regenerated by sync-versions.py (icu's\n"
        "# retentionHook). Shared with icu-data and pkgs/default.nix's shipped list.\n"
        f"[{body}]\n"
    )
    added = [f"icu{m}" for m in majors if m not in old_majors]
    dropped = [f"icu{m}" for m in old_majors if m not in majors]
    parts = []
    if added:
        parts.append("added " + ", ".join(added))
    if dropped:
        parts.append("dropped " + ", ".join(dropped))
    print("versions.nix: " + ("; ".join(parts) if parts else "reordered"))


if __name__ == "__main__":
    main()
