kind: wasmer.io/App.v0
name: python-registry
owner: wasmer
package: wasmer/static-web-server
volumes:
  - name: index
    mount: /public
app_id: da_RMMIrt4UYeW8

domains:
  - python-registry.wasix.org
