# The pure PyPI wheels the registry tests resolve against, pinned so a nix
# sandbox with no network can serve them. The registry serves only what PyPI
# cannot (native or wasix-patched); a resolver pointed at it beside PyPI takes
# every pure dependency from PyPI, which this stands in for. mirror-lock.json is
# regenerated by update-mirror.py; the layout script is anybuild's, the one
# place a PyPI pin set becomes a PEP 503 tree.
{pkgs}: let
  lock = builtins.fromJSON (builtins.readFile ./mirror-lock.json);
  dists =
    map (dist: {
      inherit (dist) project version;
      files =
        map (file: {
          inherit (file) filename sha256;
          path = pkgs.fetchurl {
            inherit (file) url sha256;
            name = file.filename;
          };
        })
        dist.files;
    })
    lock.dists;
in
  pkgs.runCommand "wasix-python-pypi-mirror" {
    nativeBuildInputs = [pkgs.python3];
    distsJson = builtins.toJSON dists;
    passAsFile = ["distsJson"];
  } ''
    python3 ${../overlays/a/anybuild/tests/make-mirror-index.py} "$distsJsonPath" "$out"
  ''
