# The PyPI side of the two indexes an anybuild python build resolves against,
# pinned so the tests can serve it instead of reaching pypi.org. mirror-lock.json
# is regenerated by `nix run .#scripts.anybuild-mirror`; one version per project
# across every covered template, so the resolution inside a test has no choice
# left to make.
#
# Its `templates` list is every python template except python-django, whose
# local venv compiles mysqlclient from source (PyPI has no wheel) and so needs
# a MySQL client library on the build host.
{pkgs}: let
  lock = builtins.fromJSON (builtins.readFile ./mirror-lock.json);

  dists =
    map (dist: {
      inherit (dist) project version;
      files =
        map (file: {
          inherit (file) filename sha256;
          path = pkgs.fetchurl {
            inherit (file) url sha256;
            name = file.filename;
          };
        })
        dist.files;
    })
    lock.dists;
  mirror =
    pkgs.runCommand "anybuild-pypi-mirror" {
      nativeBuildInputs = [pkgs.python3];
      distsJson = builtins.toJSON dists;
      passAsFile = ["distsJson"];
    } ''
      python3 ${./make-mirror-index.py} "$distsJsonPath" "$out"
    '';
in {
  inherit (lock) templates providers requirements;
  inherit mirror;
}
