# Build a Wasmer (webc) package from a wasix package derivation.
#
# Everything is DERIVED from the package; deviations live in the package's
# `passthru.wasmer` (so the wasmer intent is co-located with the package, and
# there are no separate per-program wasmer files):
#   name        ? meta.mainProgram or pname        (e.g. git-minimal -> "git")
#   version     ? toSemver package.version          (3.12 -> 3.12.0)
#   description ? meta.description
#   license     ? meta.license (spdxId/shortName)
#   owner       ? "wasmer"
#   commands    ? null  => one command per bin/*.wasm (auto-globbed at build)
#   commandEnv  ? {}     => { <command> = { ENV = "val"; }; } merged onto a command
#   fs          ? {}     => semantic mounts, e.g. { "/etc/ssl" = "${cacert}/etc/ssl"; }
#   selfMounts  ? []     => explicit store-path-at-itself mounts
#   autoSelfMount ? false => also scan bin/*.wasm for embedded /nix/store paths
#                            and mount each at itself (for binaries that exec
#                            siblings / embed other wasm, e.g. git -> bash + libexec)
{
  lib,
  pkgs,
}: {package}: let
  w = package.passthru.wasmer or {};

  # Coerce a version to a valid semver MAJOR.MINOR.PATCH for the webc manifest
  # (wasmer rejects anything else). Take the leading numeric runs, padding/
  # truncating to three: "9.0" -> "9.0.0", "685" -> "685.0.0", and GNU
  # patch-level versions like bash "5.3p9" -> "5.3.9".
  toSemver = v: let
    digits = builtins.filter (s: builtins.isString s && s != "") (builtins.split "[^0-9]+" v);
    padded = lib.take 3 (digits ++ ["0" "0" "0"]);
  in
    lib.concatStringsSep "." padded;

  name = w.name or package.meta.mainProgram or package.pname or package.name;
  owner = w.owner or "wasmer";
  version = w.version or (toSemver (package.version or "0.0.0"));
  description =
    w.description
    or (
      if package ? meta && package.meta ? description && package.meta.description != null
      then package.meta.description
      else "Autogenerated Wasmer package for ${name}"
    );
  license =
    w.license
    or (let
      l = package.meta.license or null;
    in
      if l == null
      then null
      else l.spdxId or l.shortName or null);
  entrypoint = w.entrypoint or null;
  commands = w.commands or null;
  commandEnv = w.commandEnv or {};
  defaultRunner = w.defaultRunner or "https://webc.org/runner/wasi";
  metadata = w.metadata or {};
  fs = w.fs or {};
  selfMounts = w.selfMounts or [];
  autoSelfMount = w.autoSelfMount or false;

  wrapWasmerPackage = pkgs.callPackage ./wrap-wasmer-package.nix {};

  commandLines =
    if commands == null
    then ""
    else
      lib.concatMapStringsSep "\n" (
        cmd: let
          commandName = cmd.name;
          moduleName = cmd.module or commandName;
          wasmFile = cmd.wasm or "${commandName}.wasm";
          outputFile = cmd.output or "${commandName}.wasm";
          runner = cmd.runner or defaultRunner;
          mainArgs = builtins.toJSON (cmd.mainArgs or null);
          atom = builtins.toJSON (cmd.atom or moduleName);
          env = builtins.toJSON (
            if cmd ? env
            then lib.mapAttrsToList (k: v: "${k}=${v}") cmd.env
            else null
          );
        in "${commandName}|${moduleName}|${wasmFile}|${outputFile}|${runner}|${mainArgs}|${atom}|${env}"
      )
      commands;

  # name -> JSON array of "KEY=value", consulted by the auto-glob path so a
  # globbed command can still carry env (e.g. git's SSL_CERT_FILE).
  commandEnvDecl = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (
      cmd: env: "command_env[${lib.escapeShellArg cmd}]=${lib.escapeShellArg (builtins.toJSON (lib.mapAttrsToList (k: v: "${k}=${v}") env))}"
    )
    commandEnv
  );

  extraMetadataLines =
    if metadata == {}
    then ""
    else
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (
          k: v: "${builtins.toJSON k} = ${builtins.toJSON v}"
        )
        metadata
      );

  # `selfMounts` covers mounting a store path at itself. Writing that via
  # `fs = { ${toString src} = src; }` is rejected by Nix (it refuses an attr
  # name carrying a store-path reference), so the dependency rides on `src` and
  # we strip the reference off the virt side.
  fsEntries =
    (lib.mapAttrsToList (virt: src: {inherit virt src;}) fs)
    ++ (map (src: {
        virt = builtins.unsafeDiscardStringContext (toString src);
        inherit src;
      })
      selfMounts);
in
  pkgs.stdenvNoCC.mkDerivation (finalAttrs: {
    name = "wasmer-package-${name}";
    passthru.shim = wrapWasmerPackage {
      package = finalAttrs.finalPackage;
      inherit name;
    };
    buildCommand = ''
        set -euo pipefail

        pkg_dir="$out/pkg/${name}"
        bin_dir="$pkg_dir/bin"
        mkdir -p "$bin_dir"
        declare -A module_seen
        declare -A command_env
        ${commandEnvDecl}

        cat > "$pkg_dir/wasmer.toml" <<EOF
      [package]
      name = ${builtins.toJSON "${owner}/${name}"}
      version = ${builtins.toJSON version}
      description = ${builtins.toJSON description}
      ${
        if license == null
        then ""
        else "license = ${builtins.toJSON license}"
      }
      ${
        if entrypoint == null
        then ""
        else "entrypoint = ${builtins.toJSON entrypoint}"
      }
      public = true
      EOF

        ${
        if metadata == {}
        then ""
        else ''
                cat >> "$pkg_dir/wasmer.toml" <<EOF

          [package.metadata]
          ${extraMetadataLines}
          EOF
        ''
      }

        append_command() {
          command_name="$1"
          module_name="$2"
          module_file="$3"
          runner="$4"
          main_args_json="$5"
          atom_json="$6"
          env_json="$7"

          if [ -z "''${module_seen[$module_name]+x}" ]; then
            module_seen["$module_name"]=1
            cat >> "$pkg_dir/wasmer.toml" <<EOF

      [[module]]
      name = "$module_name"
      source = "bin/$module_file"
      EOF
          fi

          cat >> "$pkg_dir/wasmer.toml" <<EOF
      [[command]]
      name = "$command_name"
      module = "$module_name"
      runner = "$runner"
      EOF

          if [ "$main_args_json" != "null" ] || [ "$atom_json" != "null" ] || [ "$env_json" != "null" ]; then
            cat >> "$pkg_dir/wasmer.toml" <<EOF
      [command.annotations.wasi]
      EOF
            if [ "$atom_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      atom = $atom_json
      EOF
            fi
            if [ "$main_args_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      main-args = $main_args_json
      EOF
            fi
            if [ "$env_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      env = $env_json
      EOF
            fi
          fi
        }

        ${
        if commands == null
        then ''
          found_any=0
          if [ -d "${package}/bin" ]; then
            while IFS= read -r -d "" wasm_path; do
              found_any=1
              wasm_file="$(basename "$wasm_path")"
              command_name="''${wasm_file%.wasm}"
              module_name="$command_name"
              output_file="$command_name.wasm"

              cp -f "$wasm_path" "$bin_dir/$output_file"
              append_command "$command_name" "$module_name" "$output_file" "${defaultRunner}" "null" "\"$module_name\"" "''${command_env[$command_name]:-null}"
            done < <(${pkgs.findutils}/bin/find "${package}/bin" -maxdepth 1 -type f -name '*.wasm' -print0)
          fi

          if [ "$found_any" -eq 0 ]; then
            echo "No .wasm binaries found in ${package}/bin for ${name}" >&2
            exit 1
          fi
        ''
        else ''
              while IFS='|' read -r command_name module_name wasm_file output_file runner main_args_json atom_json env_json; do
                [ -n "$command_name" ] || continue
                source_path="${package}/bin/$wasm_file"
                if [ ! -f "$source_path" ]; then
                  echo "Missing declared wasm binary: $source_path" >&2
                  exit 1
                fi

                cp -f "$source_path" "$bin_dir/$output_file"
                append_command "$command_name" "$module_name" "$output_file" "$runner" "$main_args_json" "$atom_json" "$env_json"
              done <<'EOF'
          ${commandLines}
          EOF
        ''
      }

        # --- filesystem mounts -------------------------------------------------
        fs_started=0
        ensure_fs_header() {
          if [ "$fs_started" -eq 0 ]; then
            printf '\n[fs]\n' >> "$pkg_dir/wasmer.toml"
            fs_started=1
          fi
        }
        add_mount() {
          # virt src  (mount store path/dir `src` at virtual path `virt`)
          local virt="$1" src="$2" target
          ensure_fs_header
          target="$pkg_dir/fs$virt"
          mkdir -p "$(dirname "$target")"
          ${pkgs.coreutils}/bin/cp -R --no-preserve=mode,ownership "$src" "$target"
          chmod -R u+w "$(dirname "$target")"
          printf '"%s" = "fs%s"\n' "$virt" "$virt" >> "$pkg_dir/wasmer.toml"
        }

        ${lib.concatMapStringsSep "\n" (e: ''
          add_mount ${lib.escapeShellArg e.virt} ${lib.escapeShellArg "${e.src}"}
        '')
        fsEntries}

        ${lib.optionalString autoSelfMount ''
        # Mount every /nix/store path embedded in the shipped wasm at itself, so
        # absolute paths the binary execs (sibling helpers, other wasm) resolve.
        while IFS= read -r sp; do
          [ -n "$sp" ] || continue
          [ -e "$sp" ] || continue
          add_mount "$sp" "$sp"
        # Split on NUL first: store-path strings in the wasm are NUL-terminated, and a bare
        # `grep -a` would glue a path to the next string (e.g. <prefix>argument), yielding a
        # non-existent path that gets skipped. tr '\0' '\n' separates them.
        done < <(${pkgs.coreutils}/bin/cat "$bin_dir"/*.wasm 2>/dev/null | ${pkgs.coreutils}/bin/tr '\0' '\n' \
          | ${pkgs.gnugrep}/bin/grep -ohE '/nix/store/[a-z0-9]{32}-[^"'"'"' ]*' \
          | ${pkgs.gnused}/bin/sed -E 's#(/nix/store/[a-z0-9]{32}-[^/]*).*#\1#' \
          | LC_ALL=C sort -u)
      ''}
    '';
  })
