{ lib, pkgs }:
{
  name,
  owner ? "wasmer",
  packageName ? name,
  version ? "0.1.0",
  description ? "Autogenerated plain Wasmer package for ${packageName}",
  entrypoint ? null,
  dependencies ? { },
  commands ? [ ],
}:
let
  dependencyLines =
    if dependencies == { } then
      ""
    else
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (depName: depVersion:
          "${builtins.toJSON depName} = ${builtins.toJSON depVersion}"
        ) dependencies
      );

  commandLines = lib.concatMapStringsSep "\n" (cmd:
    let
      commandName = cmd.name;
      moduleName = cmd.module or commandName;
      runner = cmd.runner or "https://webc.org/runner/wasi";
    in
    "${commandName}|${moduleName}|${runner}"
  ) commands;
in
pkgs.runCommand "wasmer-plain-package-${name}" { } ''
  set -euo pipefail

  pkg_dir="$out/pkg/${name}"
  mkdir -p "$pkg_dir"

  cat > "$pkg_dir/wasmer.toml" <<EOF
[package]
name = ${builtins.toJSON "${owner}/${packageName}"}
version = ${builtins.toJSON version}
description = ${builtins.toJSON description}
${if entrypoint == null then "" else "entrypoint = ${builtins.toJSON entrypoint}"}
EOF

  ${if dependencies == { } then ""
    else ''
      cat >> "$pkg_dir/wasmer.toml" <<EOF

[dependencies]
${dependencyLines}
EOF
    ''
  }

  ${if commands == [ ] then ""
    else ''
      while IFS='|' read -r command_name module_name runner; do
        [ -n "$command_name" ] || continue

        cat >> "$pkg_dir/wasmer.toml" <<EOF

[[command]]
name = "$command_name"
module = "$module_name"
runner = "$runner"
EOF
      done <<'EOF'
${commandLines}
EOF
    ''
  }
''
