# Build a Wasmer (webc) package from a wasix package derivation. Defaults are
# derived from the package; overrides live in its `passthru.wasmer`:
#   name        ? meta.mainProgram or pname        (e.g. git-minimal -> "git")
#   version     ? toSemver package.version          (3.12 -> 3.12.0)
#                 a function upstreamVersion -> semver, for versions toSemver
#                 refuses; never a literal, it would freeze across bumps
#   description ? meta.description
#   license     ? meta.license (spdxId/shortName)
#   owner       ? "wasmer"
#   commands    ? null  => one command per bin/*.wasm (auto-globbed at build)
#   env         ? {}     => { ENV = "val"; } set on every command
#   commandEnv  ? {}     => { <command> = { ENV = "val"; }; } merged onto a command
#   dependencies ? [] => derivations, or { package = drv; version = requirement; }
#   fs          ? {}     => mounts, e.g. { "/etc/ssl" = "${cacert}/etc/ssl"; }
#   selfMounts  ? []     => explicit store-path-at-itself mounts
#   autoSelfMount ? false => also scan bin/*.wasm for embedded /nix/store paths
#                            and mount each at itself
{
  lib,
  pkgs,
  # wasmer runtime, used to build each dependency's .webc.
  wasmer,
  # this function itself, to build dependency webcs.
  self,
  wasmerDependencies,
  posOf,
}: {
  package,
  # every baseVersion this webc name ships (registry history); the wasmer
  # layer passes it so the staleRels note doesn't flag sibling versions.
  # null: this package's version is the only one.
  servedVersions ? null,
}: let
  # the wasmer package and its webc point back at the package definition
  packagePos = posOf package;
  w = package.passthru.wasmer or {};
  ciTags = (package.passthru.wasix or {}).ciTags or [];
  ciWasix = {inherit publication;} // lib.optionalAttrs (ciTags != []) {inherit ciTags;};

  ident = import ./ident.nix {inherit lib;};
  inherit (ident) rels webcIdent;

  inherit (webcIdent package) name owner version baseVersion rel;
  publication = {
    version = baseVersion;
    inherit rel;
  };

  # rels.json keys no served version carries: left behind by an upstream bump;
  # the update driver drops them (regen hook on nixpkgs), this note covers
  # bumps made by hand.
  staleRels = lib.filter (v:
    !(lib.elem v (
      if servedVersions != null
      then servedVersions
      else [baseVersion]
    )))
  (lib.attrNames (rels."wasmerPackages.${name}" or {}));
  description =
    w.description
    or (
      if package ? meta && package.meta ? description && package.meta.description != null
      then package.meta.description
      else "Autogenerated Wasmer package for ${name}"
    );
  license =
    w.license
    or (let
      l = package.meta.license or null;
    in
      if l == null
      then null
      else l.spdxId or l.shortName or null);
  entrypoint = w.entrypoint or null;
  commands = w.commands or null;
  packageEnv = w.env or {};
  commandEnv = w.commandEnv or {};
  # wasmer.toml wants a JSON array of "KEY=value"; null when a command sets none.
  envJson = e:
    builtins.toJSON (
      if e == {}
      then null
      else lib.mapAttrsToList (k: v: "${k}=${v}") e
    );
  defaultRunner = w.defaultRunner or "https://webc.org/runner/wasi";
  # meta.position points into the store source copy; repo-relative "path:line"
  # for the publish-time source link
  sourceRef = let
    m =
      if packagePos == null
      then null
      else builtins.match "^/nix/store/[^/]+/(.*)$" packagePos.file;
  in
    if m == null
    then null
    else "${builtins.head m}:${toString packagePos.line}";
  homepage = let
    h = (package.meta or {}).homepage or null;
  in
    if builtins.isString h
    then h
    else null;

  metadata =
    {wasix-rel = rel;}
    // lib.optionalAttrs (sourceRef != null) {wasix-source = sourceRef;}
    // (w.metadata or {});

  # registry-visible package page; the publish step appends the pinned source
  # link, rev, and rebuild command
  readme =
    lib.concatStringsSep "\n" (
      ["# ${name}" "" description]
      ++ lib.optionals (homepage != null) ["" "Upstream: <${homepage}>"]
      ++ lib.optionals (rel > 1) ["" "Build ${toString rel} of this version."]
    )
    + "\n";
  fs = w.fs or {};
  selfMounts = w.selfMounts or [];
  autoSelfMount = w.autoSelfMount or false;

  # Wasix packages this one execs at runtime; each becomes a webc
  # [dependencies] entry. At load wasmer places each dependency's command atoms
  # at /bin/<cmd> and /usr/bin/<cmd> in this package's fs, so e.g. /bin/bash
  # resolves from the dependency instead of a bundled copy.
  dependencies = w.dependencies or [];
  dependencySpecs = map wasmerDependencies.normalize dependencies;
  dependencyLines =
    lib.concatMapStringsSep "\n" (
      dep: let
        r = webcIdent dep.package;
      in "${builtins.toJSON r.fullName} = ${builtins.toJSON dep.version}"
    )
    dependencySpecs;

  # Dependency webcs and their transitive closure, symlinkJoined (via each
  # .webc) into one --include-webc tree for the shim.
  depWebcs = map (dep: self {package = dep.package;}) dependencySpecs;
  closure = webcs: lib.unique (webcs ++ lib.concatMap (w: closure w.depWebcs) webcs);
  depTree =
    if depWebcs == []
    then null
    else
      pkgs.symlinkJoin {
        name = "webc-deps-${name}";
        paths = map (w: w.webc) (closure depWebcs);
      };

  wrapWasmerPackage = pkgs.callPackage ./wrap-wasmer-package.nix {};

  commandLines =
    if commands == null
    then ""
    else
      lib.concatMapStringsSep "\n" (
        cmd: let
          commandName = cmd.name;
          moduleName = cmd.module or commandName;
          wasmFile = cmd.wasm or "${commandName}.wasm";
          outputFile = cmd.output or "${commandName}.wasm";
          runner = cmd.runner or defaultRunner;
          mainArgs = builtins.toJSON (cmd.mainArgs or null);
          atom = builtins.toJSON (cmd.atom or moduleName);
          env = envJson (packageEnv // (cmd.env or {}));
        in "${commandName}|${moduleName}|${wasmFile}|${outputFile}|${runner}|${mainArgs}|${atom}|${env}"
      )
      commands;

  # command name -> JSON array of "KEY=value", so auto-globbed commands can
  # still carry env (e.g. git's SSL_CERT_FILE). A command naming none inherits
  # package_env.
  commandEnvDecl = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (
      cmd: env: "command_env[${lib.escapeShellArg cmd}]=${lib.escapeShellArg (envJson (packageEnv // env))}"
    )
    commandEnv
  );

  extraMetadataLines =
    if metadata == {}
    then ""
    else
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (
          k: v: "${builtins.toJSON k} = ${builtins.toJSON v}"
        )
        metadata
      );

  # selfMounts mounts a store path at itself. Nix rejects attr names carrying
  # store-path references, so the virt side gets its string context stripped
  # while src keeps the dependency.
  fsEntries =
    (lib.mapAttrsToList (virt: src: {inherit virt src;}) fs)
    ++ (map (src: {
        virt = builtins.unsafeDiscardStringContext (toString src);
        inherit src;
      })
      selfMounts);
in
  pkgs.stdenvNoCC.mkDerivation (finalAttrs: {
    name = "wasmer-package-${name}";
    pos = packagePos;
    inherit readme;
    passAsFile = ["readme"];
    passthru = {
      id = {inherit owner name version baseVersion;};
      wasix = ciWasix;
      # depTree is the closure as one --include-webc tree, null when there are no
      # dependencies; a consumer assembling its own offline tree needs it, since
      # a package's own webc carries no dependency.
      inherit depWebcs depTree;
      # The built webc at owner/name/version.webc, ready to symlinkJoin into an
      # --include-webc tree. Its .shim drives this packed artifact (what ships),
      # vs the pkg .shim below which drives the wasmer.toml source dir.
      webc = let
        built = pkgs.runCommand "webc-${owner}-${name}-${version}" ({
            passthru.wasix =
              ciWasix
              // {
                updateNotes = lib.optional (staleRels != []) {
                  message = "rels.json has stale keys (${lib.concatMapStringsSep ", " (v: "wasmerPackages.${name} ${v}") staleRels}); nix run .#update -- nixpkgs drops them";
                  when = _: _: true;
                };
              };
          }
          // pkgs.lib.optionalAttrs (packagePos != null) {pos = packagePos;}) ''
          d="$out/${owner}/${name}"
          mkdir -p "$d"
          ${wasmer}/bin/wasmer package build --quiet "${finalAttrs.finalPackage}/pkg/${name}" -o "$d/${version}.webc"
        '';
      in
        built
        // {
          shim = wrapWasmerPackage {
            package = finalAttrs.finalPackage;
            inherit name depTree;
            pname = package.pname or null;
            version = package.version or null;
            runTarget = "${built}/${owner}/${name}/${version}.webc";
          };
        };
      shim = wrapWasmerPackage {
        package = finalAttrs.finalPackage;
        inherit name depTree;
        pname = package.pname or null;
        version = package.version or null;
      };
    };
    buildCommand = ''
        set -euo pipefail

        pkg_dir="$out/pkg/${name}"
        bin_dir="$pkg_dir/bin"
        mkdir -p "$bin_dir"
        declare -A module_seen
        declare -A command_env
        package_env=${lib.escapeShellArg (envJson packageEnv)}
        ${commandEnvDecl}

        cat > "$pkg_dir/wasmer.toml" <<EOF
      [package]
      name = ${builtins.toJSON "${owner}/${name}"}
      version = ${builtins.toJSON version}
      description = ${builtins.toJSON description}
      readme = "README.md"
      ${
        if license == null
        then ""
        else "license = ${builtins.toJSON license}"
      }
      ${
        if entrypoint == null
        then ""
        else "entrypoint = ${builtins.toJSON entrypoint}"
      }
      public = true
      EOF

        cp "$readmePath" "$pkg_dir/README.md"

        ${
        if metadata == {}
        then ""
        else ''
                cat >> "$pkg_dir/wasmer.toml" <<EOF

          [package.metadata]
          ${extraMetadataLines}
          EOF
        ''
      }

        ${lib.optionalString (dependencies != []) ''
              cat >> "$pkg_dir/wasmer.toml" <<EOF

        [dependencies]
        ${dependencyLines}
        EOF
      ''}

        append_command() {
          command_name="$1"
          module_name="$2"
          module_file="$3"
          runner="$4"
          main_args_json="$5"
          atom_json="$6"
          env_json="$7"

          if [ -z "''${module_seen[$module_name]+x}" ]; then
            module_seen["$module_name"]=1
            cat >> "$pkg_dir/wasmer.toml" <<EOF

      [[module]]
      name = "$module_name"
      source = "bin/$module_file"
      EOF
          fi

          cat >> "$pkg_dir/wasmer.toml" <<EOF
      [[command]]
      name = "$command_name"
      module = "$module_name"
      runner = "$runner"
      EOF

          if [ "$main_args_json" != "null" ] || [ "$atom_json" != "null" ] || [ "$env_json" != "null" ]; then
            cat >> "$pkg_dir/wasmer.toml" <<EOF
      [command.annotations.wasi]
      EOF
            if [ "$atom_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      atom = $atom_json
      EOF
            fi
            if [ "$main_args_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      main-args = $main_args_json
      EOF
            fi
            if [ "$env_json" != "null" ]; then
              cat >> "$pkg_dir/wasmer.toml" <<EOF
      env = $env_json
      EOF
            fi
          fi
        }

        ${
        if commands == null
        then ''
          found_any=0
          if [ -d "${package}/bin" ]; then
            while IFS= read -r -d "" wasm_path; do
              found_any=1
              wasm_file="$(basename "$wasm_path")"
              command_name="''${wasm_file%.wasm}"
              module_name="$command_name"
              output_file="$command_name.wasm"

              cp -f "$wasm_path" "$bin_dir/$output_file"
              append_command "$command_name" "$module_name" "$output_file" "${defaultRunner}" "null" "\"$module_name\"" "''${command_env[$command_name]:-$package_env}"
            done < <(${pkgs.findutils}/bin/find "${package}/bin" -maxdepth 1 -type f -name '*.wasm' -print0)
          fi

          if [ "$found_any" -eq 0 ]; then
            echo "No .wasm binaries found in ${package}/bin for ${name}" >&2
            exit 1
          fi
        ''
        else ''
              while IFS='|' read -r command_name module_name wasm_file output_file runner main_args_json atom_json env_json; do
                [ -n "$command_name" ] || continue
                source_path="${package}/bin/$wasm_file"
                if [ ! -f "$source_path" ]; then
                  echo "Missing declared wasm binary: $source_path" >&2
                  exit 1
                fi

                cp -f "$source_path" "$bin_dir/$output_file"
                append_command "$command_name" "$module_name" "$output_file" "$runner" "$main_args_json" "$atom_json" "$env_json"
              done <<'EOF'
          ${commandLines}
          EOF
        ''
      }

        # --- filesystem mounts -------------------------------------------------
        fs_started=0
        ensure_fs_header() {
          if [ "$fs_started" -eq 0 ]; then
            printf '\n[fs]\n' >> "$pkg_dir/wasmer.toml"
            fs_started=1
          fi
        }
        add_mount() {
          # virt src  (mount store path/dir `src` at virtual path `virt`)
          local virt="$1" src="$2" target
          ensure_fs_header
          target="$pkg_dir/fs$virt"
          mkdir -p "$(dirname "$target")"
          ${pkgs.coreutils}/bin/cp -R --no-preserve=mode,ownership "$src" "$target"
          chmod -R u+w "$(dirname "$target")"
          printf '"%s" = "fs%s"\n' "$virt" "$virt" >> "$pkg_dir/wasmer.toml"
        }

        ${lib.concatMapStringsSep "\n" (e: ''
          add_mount ${lib.escapeShellArg e.virt} ${lib.escapeShellArg "${e.src}"}
        '')
        fsEntries}

        ${lib.optionalString autoSelfMount ''
        # Mount every /nix/store path embedded in the shipped wasm at itself, so
        # absolute paths the binary execs (sibling helpers, other wasm) resolve.
        while IFS= read -r sp; do
          [ -n "$sp" ] || continue
          [ -e "$sp" ] || continue
          add_mount "$sp" "$sp"
        # Split on NUL first: store-path strings in the wasm are NUL-terminated, and a bare
        # `grep -a` would glue a path to the next string (e.g. <prefix>argument), yielding a
        # non-existent path that gets skipped.
        done < <(${pkgs.coreutils}/bin/cat "$bin_dir"/*.wasm 2>/dev/null | ${pkgs.coreutils}/bin/tr '\0' '\n' \
          | ${pkgs.gnugrep}/bin/grep -ohE '/nix/store/[a-z0-9]{32}-[^"'"'"' ]*' \
          | ${pkgs.gnused}/bin/sed -E 's#(/nix/store/[a-z0-9]{32}-[^/]*).*#\1#' \
          | LC_ALL=C sort -u)
      ''}
    '';
  })
